#!/bin/bash

CARBON_LOGS=/opt/graphite/storage/log/carbon-cache/

# gzip log files that are not gzipped already and are older than 3 days
find $CARBON_LOGS -type f ! -name '*gz' -mtime +3 -exec gzip -f -q "{}" \;
# removes log files older than 30 days
find $CARBON_LOGS -type f -ctime +30 -exec rm "{}" \;
